---
- name: Deploy Prebuilt Spring Boot Hello World on Amazon Linux 2023
  hosts: ec2
  become: true

  tasks:
    # -------------------------------
    # Java 21 (Amazon Corretto)
    # -------------------------------
    - name: Ensure Java 21 is installed
      dnf:
        name: java-21-amazon-corretto
        state: present

    - name: Verify Java version
      command: java -version
      register: java_version_output
      ignore_errors: true

    - name: Show Java version
      debug:
        var: java_version_output.stderr_lines

    # -------------------------------
    # Hello World アプリ配置・起動
    # -------------------------------
    - name: Create app directory
      file:
        path: /home/ec2-user/app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Download prebuilt Hello World JAR
      get_url:
        url: "https://github.com/spring-guides/gs-spring-boot/releases/download/v2.3.0.RELEASE/gs-spring-boot-0.1.0.jar"
        dest: /home/ec2-user/app/demo.jar
        mode: '0755'
        owner: ec2-user
        group: ec2-user

    - name: Stop existing app if running
      shell: pgrep -f 'java -jar' | xargs -r kill
      ignore_errors: true

    - name: Start Spring Boot Hello World app
      shell: nohup java -jar /home/ec2-user/app/demo.jar > /home/ec2-user/app/app.log 2>&1 &
      become_user: ec2-user

    - name: Wait for app to start
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 8080
        delay: 5
        timeout: 60

    - name: Verify Hello World response
      uri:
        url: "http://{{ inventory_hostname }}:8080"
        return_content: yes
      register: result

    - name: Print app response
      debug:
        msg: "{{ result.content }}"
