---
- name: Install Java 21 on Amazon Linux 2023
  hosts: all
  become: true

  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest

    - name: Install Amazon Corretto 21 (Java 21)
      dnf:
        name: java-21-amazon-corretto
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version_output
      ignore_errors: true

    - name: Show Java version output
      debug:
        var: java_version_output.stderr_lines
