name: Ansible Deploy Java 21

on:
  workflow_dispatch:

jobs:
  ansible-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform  # Terraform用ディレクトリを指定

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - name: Terraform Init
        run: terraform init

      - name: Get EC2 Public IP from Terraform output
        run: |
          echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts

      - name: Create Ansible inventory dynamically
        working-directory: ./ansible  # ← ansibleのディレクトリに戻る
        run: |
          echo "[ec2]" > inventory.ini
          echo "$EC2_IP ansible_user=ec2-user" >> inventory.ini

      - name: Run Ansible Playbook (Install Java 21)
        working-directory: ./ansible
        run: |
          ansible-playbook -i inventory.ini playbook.yml
