name: Ansible CI

on:
  workflow_run:
    workflows: ["Terraform CD"]
    types:
      - completed
  workflow_dispatch:

jobs:
  ansible-dry-run:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # GitHubリポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # AWS認証（S3バックエンドにアクセスするため）
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # Terraformセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraformの出力からEC2のIPを取得（S3からtfstateを読み込み）
      - name: Get EC2 public IP from Terraform output
        id: get_ip
        run: |
          cd terraform
          terraform init -reconfigure
          echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV

      - name: Display EC2 IP
        run: echo "EC2 IP is ${{ env.EC2_IP }}"

      # Ansibleインストール
      - name: Install Ansible
        run: |
          sudo apt update -y
          sudo apt install -y ansible

      # SSH秘密鍵設定
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 動的インベントリ作成（最新IP使用）
      - name: Create dynamic inventory
        working-directory: ./ansible
        run: |
          echo "[ec2]" > inventory.ini
          echo "${{ env.EC2_IP }}" >> inventory.ini

      # SSH known_hosts 登録
      - name: Add EC2 to known_hosts
        run: ssh-keyscan -H ${{ env.EC2_IP }} >> ~/.ssh/known_hosts

      # EC2起動待ち
      - name: Wait for EC2 to be ready
        run: sleep 30

      # SSH接続確認
      - name: Test SSH connection
        run: ssh -i ~/.ssh/id_rsa ec2-user@${{ env.EC2_IP }} "echo 'SSH connection successful (Dry Run)!'"

      # Ansible Dry Run (--check)
      - name: Ansible Dry Run (--check)
        working-directory: ./ansible
        run: ansible-playbook -i inventory.ini playbook.yaml --check
