name: Terraform CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches: [main]
    paths:
      - "課題41terraform/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
      TF_VAR_key_name: ${{ secrets.KEY_NAME }}
      TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}

    defaults:
      run:
        working-directory: 課題41terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Test
        run: terraform test terraform/tests/test-ci.tftest -filter "test-ci"
