name: Terraform CI

on:
  pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ap-northeast-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.1

      - name: Terraform Init
        run: terraform init
        working-directory: 課題41terraform

      - name: Terraform Fmt
        run: terraform fmt -recursive
        working-directory: 課題41terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: 課題41terraform

      - name: Terraform Test (CI)
        run: |
          terraform test terraform/tests/test-ci.tftest -filter "test-ci" \
            -var "key_name=${{ secrets.KEY_NAME }}" \
            -var "rds_password=${{ secrets.RDS_PASSWORD }}"
        working-directory: 課題41terraform
