name: Terraform CD

on:
  push:
    branches:
      - main
    paths:
      - "課題41terraform/**"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.1

      - name: Terraform Init
        run: terraform init
        working-directory: 課題41terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var "key_name=${{ secrets.KEY_NAME }}" \
            -var "rds_password=${{ secrets.RDS_PASSWORD }}" \
            -var "ec2_count=2"
        working-directory: 課題41terraform
